module.exports = Object.freeze({
  HTTP_THIS_OPERATION_REGARD_APPLICATION: 'okm-0-0-1-op-s-3001',
  HTTP_THIS_OPERATION_DISREGARD_APPLICATION: 'okm-0-0-1-op-s-3002',
  HTTP_THIS_OPERATION_REGARD_UPDATED_LINK: 'okm-0-0-1-op-s-3004'
});