module.exports = Object.freeze({
  OPERATION_MODE_REACTIVE: 'string-profile-1-0:STRING_VALUE_TYPE_REACTIVE',
  OPERATION_MODE_PROTECTION: 'string-profile-1-0:STRING_VALUE_TYPE_PROTECTION',
  OPERATION_MODE_OFF: 'string-profile-1-0:STRING_VALUE_TYPE_OFF',
});